server:
  port: 8080

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/aiops_auth
    username: postgres
    password: proot
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: aiopsSecretKeyForJwtGenerationAndValidation123456789
  expiration: 86400000